project_id = "rfvvpfvrxxodslzdqgll"

[functions.analyze-meal]
verify_jwt = false

[functions.cycle-coach]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.premium-insights]
verify_jwt = false

[functions.monthly-analysis]
verify_jwt = false

[functions.mollie-payments]
verify_jwt = false

[functions.nutrition-coach]
verify_jwt = false

[functions.daily-analysis]
verify_jwt = false

[functions.weekly-nutrition-insight]
verify_jwt = false
